spring:
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api-oms/**
          filters:
            - StripPrefix=1

        - id: stock
          uri: lb://stock-service
          predicates:
              - Path=/api-sts/**
          filters:
              - StripPrefix=1